name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_URL = 'https://equal-boa-39842.upstash.io'
UPSTASH_REDIS_REST_TOKEN = 'AZuiAAIncDEwNDExZmY5NTE3ZDk0NGQzYmRiMDUxM2U1MGM0NGIwMnAxMzk4NDI'